### ISSUE TITLE
Instantiate a new Dictionary

### ISSUE THREAD

**Issue by Entrivax** [fusionlanguage/fut#114]
If I try to instantiate a Dictionary and return it like this:
```cs
public class Foo
{
    public static Dictionary<int, int># GetMap()
    {
        Dictionary<int, int># map = new Dictionary<int, int>();
        return map;
    }
}
```
I get the following error:
```
main.fu(5): ERROR: Cannot coerce Dictionary<undefined, undefined># to Dictionary<int, int>#
```
![image](https://github.com/fusionlanguage/fut/assets/1197915/cb4ed1d1-c717-4ee2-b867-ba6c50063c1a)

Is it maybe not the syntax to instantiate a type with generics?
I didn't find this case in the documentation.

**Comment by pfusik** [comment]
Thank you for your report! Your code is correct. Allocating collections dynamically wasn't implemented until now.

**Comment by Entrivax** [comment]
Thank you, it works! 🙏
![Screenshot_20230920_132234](https://github.com/fusionlanguage/fut/assets/1197915/023c6bed-9cb5-4120-bc97-2f1bd4940022)
