### ISSUE TITLE
`#include <stdio.h>` in `native` blocks doesn't work

### ISSUE THREAD

**Issue by iahung2** [fusionlanguage/fut#130]
### Discussed in https://github.com/fusionlanguage/fut/discussions/129

<div type='discussions-op-text'>

<sup>Originally posted by **iahung2** September 26, 2023</sup>
I think this is a bug. Please have a look. Thank you.</div>

**Comment by pfusik** [comment]
Thank you for reporting this! It is now fixed.

I noticed that you first create discussions, then issues from them. Please just create issues in the first place, even if you are unsure if that's a bug or whether the feature request is going to be accepted.
