### ISSUE TITLE
Transpile to Golang

### ISSUE THREAD

**Issue by markusbkk** [fusionlanguage/fut#137]
Any chance of ever seeing a Go(lang) transpiler for this?

**Comment by pfusik** [comment]
Yes, I think it's possible. It's been proposed in #45.

**Comment by markusbkk** [comment]
> Yes, I think it's possible. It's been proposed in #45.

Ah. Thanks. My bad. Didn't see that issue (searching for anything Go related that doesn't bear "Golang" in the title or text is always "fun").
