### ISSUE TITLE
Emit compiler directives based on language being compiled

### ISSUE THREAD

**Issue by caesay** [fusionlanguage/fut#142]
Right now it's a bit cumbersome to write implementations in native languages, one thing which could make it easier is if we could do something like `#if JS` or `#if CPP` out of the box. 

I had a look at the command line and wasn't entirely sure, but I guess fut.cpp, fut.cs, fut.java, and fut.js are not being generated and are written by hand?

Because of the way parseAndResolve/emit/emitImplicitLang works we'll need to restructure things a bit, so that the source is parsed once for each file emitted. Do you have any issues with this? If you agree with the change I can submit a PR.

**Comment by pfusik** [comment]
What's the problem to pass `-D JS` etc?

Also, perhaps we could have a nicer syntax than:

    #if JS
    native { ... }
    #endif

Maybe `native (js, ts) { ... }` ? or `native "js | ts" { .... }` ?

Yes, `fut.*` are hand-coded. They could probably be refactored to Fusion.

Only recently I changed per-language parsing to just once. I'd prefer to have as few `#if`s as possible.

**Comment by pfusik** [comment]
Also, in my ~50 KLOC of Fusion code there's just one `native`. What is your use case?

**Comment by caesay** [comment]
Probably at least half of my code is in `native{}` blocks at the moment. There are some weird things too, because the parser doesn't completely ignore code in native blocks. For example `"\0"` in a native block gives a compiler error about it being an unknown escape sequence (and there are other oddities too - single quotes to name one other). 

I think I've already mentioned a few of my use-cases. Right now I'm working on https://velopack.io/ which is a cross-platform, soon-to-be-cross-language installer/update framework for desktop apps. I am working on translating a small/minimal portion of the core update library which application authors will consume: https://github.com/velopack/velopack/tree/master/src/Velopack

So a lot of my code right now looks like this:

![image](https://github.com/fusionlanguage/fut/assets/1287295/38569d93-e512-4a93-a861-a4ed52106790)

Or like this:

![image](https://github.com/fusionlanguage/fut/assets/1287295/b6f34a5d-ab57-4989-845c-bbacca40741d)

Or like this:

![image](https://github.com/fusionlanguage/fut/assets/1287295/80d3cdcc-57bf-402b-86b2-d7bf26f239f3)

All of that platform native code is annoying, and is ultimately the reason I'm trying right now to start contributing some of the missing features myself to fusion directly. Even with the missing features and #if's and native blocks, it's still a time saver, because after the json parsing, process starting, and string utilities the rest of my library is mostly algorithmic / logic which I want to re-use and expose to application authors as a library.

**Comment by caesay** [comment]
Closing this since you don't seem keen on it
