### ISSUE TITLE
Is there some mailing list, forum, Element/Matrix chat or something for communication?

### ISSUE THREAD

**Issue by mavavilj** [fusionlanguage/fut#156]
Is there some mailing list, forum, Element/Matrix chat or something for communication?

**Comment by pfusik** [comment]
We have [Discussions](https://github.com/fusionlanguage/fut/discussions).

**Comment by mavavilj** [comment]
Okay I didn't find mention of this anywhere.

**Comment by pfusik** [comment]
It's in the top menu of GitHub and at the very end of [Getting Started](https://github.com/fusionlanguage/fut/blob/master/doc/getting-started.md).

**Comment by mavavilj** [comment]
I tried to search that for keywords like "communication" or "mailing-list". It didn't find it.

**Comment by mavavilj** [comment]
I tried to search that, but guess I used the wrong keywords then.

**Comment by mavavilj** [comment]
Or if it listed the headings in some sort of index.

**Comment by mavavilj** [comment]
See, e.g. this doesn't bring up it:

https://github.com/search?q=repo%3Afusionlanguage%2Ffut%20communication&type=code
