### ISSUE TITLE
What exactly guarantees that all of the produced codes have exactly the same behavior?

### ISSUE THREAD

**Issue by mavavilj** [fusionlanguage/fut#157]
What exactly guarantees that all of the produced codes have exactly the same behavior?

I want to trust that the resulting codes are functionally the same, but since there can be a lot of it, verifying it manually sounds unideal.

**Comment by pfusik** [comment]
There is no guarantee of exactly same behavior for all target languages in all possible scenarios. For instance, negative-indexing an array:
- is undefined behavior in C and C++
- throws an exception in C#, D, Java
- yields `undefined` in JavaScript
- accesses elements from the end of a Python array

It's best to have automated tests for your code.

**Comment by mavavilj** [comment]
What about if we assume that the programmer does not do anything stupid, is the code on targets then the equivalent program?

**Comment by mavavilj** [comment]
Also, since tests (to me) are not always trivial, then is some input and output test sufficient to verify that the programs are correct?

**Comment by pfusik** [comment]
> What about if we assume that the programmer does not do anything stupid, is the code on targets then the equivalent program?

Yes, that's the essence of Fusion.

> Also, since tests (to me) are not always trivial, then is some input and output test sufficient to verify that the programs are correct?

There is no such thing as "universal tests". Tests are always specific to the code you write.

For example, a Fusion project called [RECOIL](https://recoil.sourceforge.net) contains a test suite of 1000+ input files and one can check if a code change doesn't break any of them by comparing the outputs with reference PNG files. In a fully automated way, of course.

`fut` itself contains hundreds of Fusion test sources, transpiles them to different languages, compiles and runs.

**Comment by mavavilj** [comment]
> There is no such thing as "universal tests". Tests are always specific to the code you write.

Yes, but I think checking Fusion code manually is certainly more complex than if one just wrote the program in one language by hand.
