### ISSUE TITLE
Duplicated symbol error reported on wrong line

### ISSUE THREAD

**Issue by iAndyHD3** [fusionlanguage/fut#161]
The following code:
```c#
public class Foo               //1
{                              //2
    public const int a = 0;    //3
    public const int a = 0;    //4
}                              //5
```
Reports an error on line 5 instead of line 4
```Foo.fu(5): ERROR: Duplicate symbol```
According to my testing, this only occurs with public const fields

However same issue with classes:
```c#
public class Bar //1
{                //2
}                //3
public class Bar //4
{                //5
}                //6
```
Reports an error on line 5 instead of line 4

**Comment by pfusik** [comment]
Thanks for reporting!
