### ISSUE TITLE
Conditional compilation is broken

### ISSUE THREAD

**Issue by Altair-sh** [fusionlanguage/fut#165]
The following code was transpiling fine with fut 3.1.1
```cs
public static class MainClass {
    public static void Main(string[] args){
        #if CS
        native {
            // some C# code
        }
        #endif
    }
}
```
Now fut produces following errors:
```
src/MainClass.fu(3): ERROR: Invalid expression
src/MainClass.fu(3): ERROR: Expected ';', got 'if'
```
The error can be avoided by removing the indent before `#if`. 
```cs
public static class MainClass {
    public static void Main(string[] args){
#if CS
        //...
```
Please fix this or add a note in documentation about indentaion.

**Comment by Altair-sh** [comment]
I checked several fut versions and it seems something in 3.2.0 breaks conditional compilation. 3.1.2 works fine.

**Comment by pfusik** [comment]
Indeed, this was introduced in 3.2.0. Thanks for reporting!
