### ISSUE TITLE
[Feature Request] Introduce size_t type to language

### ISSUE THREAD

**Issue by al1-ce** [fusionlanguage/fut#166]
Since 4 languages use it for array length it'd be beneficial to have it.

What it'd transpile to:
- C, C++, D, OpenCL C - `size_t` (typedef/alias to int/long depending on 32/64bit platform)
- C#, Java, Swift - `int` (seems to not have any distinction)
- JavaScript, Python - nothing (dynamic types, no way to emit type of variable)
- TypeScript - `number` (no other distinct numeric types)

Partially related to #97

**Comment by pfusik** [comment]
In .NET there's `Array.LongLength` and arrays can be subscripted by `long`s. Unlike `List`s.

In JavaScript and Python _arrays_ of numeric types are typed. So the size type needs to be defined somehow.

**Comment by pfusik** [comment]
C# has `nint` and `nuint`.

**Comment by pfusik** [comment]
Swift's `Int` type is pointer-sized. fut emits it for both `nint` and `int` because it feels native to Swift - its API rarely uses `Int32`.

Emiting `nint` in C# broke [UWP](https://en.wikipedia.org/wiki/Universal_Windows_Platform) so I reverted to `int` for now.
