### ISSUE TITLE
Add some basic examples and or syntax documentation

### ISSUE THREAD

**Issue by ChillerDragon** [fusionlanguage/fut#170]
I am having a hard time finding some examples or documentation on the syntax. There are example projects but that seems a bit overkill to learn the basics of the language. The [getting started](https://github.com/fusionlanguage/fut/blob/9115d96198d0de8c92f92b7e46ee8537656e9a04/doc/getting-started.md#hello-world) section show cases a hello world and how to define classes and methods.

I was expecting some documentation listing all data types and basic language features. And maybe some examples/ folder at the root of the repository with a few files that have descriptive names of common use cases. Such as:
```
examples/Variables.fu
examples/Functions.fu
examples/Floats.fu
examples/StringFormatting.fu
examples/Arrays.fu
examples/Casting.fu
examples/BitwiseOperations.fu
examples/Loops.fu
examples/Conditions.fu
examples/Logic.fu
examples/Io.fu
```

The examples other than the hello world on the website show a lot of the syntax https://fusion-lang.org/#qoi but it is a bit too hidden in my opinion. Also its not easily searchable. You have to read the entire thing to understand it all instead of being able to look for "how to do xy". Also syntax such as `	byte[]#? Encoded;` is non obvious to me at first glance.

**Comment by pfusik** [comment]
Thank you for proposing this!

Right now Fusion is documented in its [language reference](https://github.com/fusionlanguage/fut/blob/master/doc/reference.md) which is linked from "getting started". On a computer, GitHub provides a hamburger-like button on the top-right that expands a table of contents. Have you read it?

I realize that this is far from perfect, especially if you are browsing on a phone.
I'd like to have it split into small, tutorial-like chapters, each one loaded separately, with more examples, yet easy to grasp completely in a matter of minutes.

Which language's documentation do you consider easily accessible to the beginners, as an inspiration?
Are you willing to share your feedback on the new tutorial content as I write it?
Would you like to share your Fusion project idea (in private if you prefer) ?

**Comment by ChillerDragon** [comment]
Oh wow I am not sure how I managed to not see https://github.com/fusionlanguage/fut/blob/master/doc/reference.md but thats good enough I think. A few example files would not hurt but I don't think they are needed that much given how complete the reference.md already is. So I will close this issue as completed (sorry for being blind).

> Which language's documentation do you consider easily accessible to the beginners, as an inspiration?

My inspiration for an examples/ folder is [this](https://github.com/LingDong-/wax/tree/main/examples). But I don't particularly like the complexity of the examples. I think its nicer if the examples are less real world programs and more dumbed down simple syntax show cases.

>  Are you willing to share your feedback on the new tutorial content as I write it?

Feel free to ping me once you are done. If I am too lazy to read it I will just ignore it :p

>  Would you like to share your Fusion project idea (in private if you prefer) ?

I am currently building a few libraries for the teeworlds network protocol. And end up rewriting the same logic multiple times just to have the code in the native language instead of some C bindings.
