### ISSUE TITLE
Example project?

### ISSUE THREAD

**Issue by nikitalita** [fusionlanguage/fut#21]
Is there an existing project written in Ć? I had been interested in this for a library that I had wanted to write, but there are no examples other than the trivial "hello world" and the tests in this repo that I've found.

**Comment by pfusik** [comment]
http://recoil.sourceforge.net
http://asap.sourceforge.net
https://github.com/pfusik/image-ci
https://github.com/pfusik/datamatrix-ci

**Comment by nikitalita** [comment]
Excellent! Thank you so much!

**Comment by pfusik** [comment]
https://github.com/pfusik/ray-ci

I'll keep this ticket open so everyone can showcase their projects.

**Comment by pfusik** [comment]
https://github.com/pfusik/qoi-ci

**Comment by pfusik** [comment]
This is how Ć translations are used in RECOIL and ASAP:

![RECOIL architecture](https://recoil.sourceforge.net/recoil-internals.png)

![ASAP architecture](https://asap.sourceforge.net/asap-internals.png)

**Comment by pfusik** [comment]
Also, cito itself is being rewritten to Ć (#48).

**Comment by pfusik** [comment]
https://github.com/pfusik/qoa-ci

**Comment by pfusik** [comment]
These projects are now listed in [Getting Started](https://github.com/fusionlanguage/fut/blob/master/doc/getting-started.md), so I'm closing this ticket. The language is now self-hosted and rebranded to Fusion.
