### ISSUE TITLE
The name is very bad

### ISSUE THREAD

**Issue by JimmyCushnie** [fusionlanguage/fut#3]
On a US keyboard, "Ć" is hard to type, and therefore both hard to talk about and hard to search for. I think this project will get more attention and use if the name is changed.

May I suggest:

* `C'` or "C Prime"
* `C*` or "C Star"
* `Ci`

**Comment by avsnarayan** [comment]
Can it be C> - C more. Thanks.

**Comment by pfusik** [comment]
Thank you for your suggestions.
Ć is next to C in my native alphabet and D was already taken.
It's funny to hear that learning one letter is "hard", while I consider learning the whole English language as easy.
The alternative spelling is "Ci", I use it in the source code and for filename extensions.

**Comment by jarble** [comment]
It's somewhat confusing to have two different names for the same programming language, so it might be better to use one of these names consistently. I prefer the "ci" spelling over "Ć," since it's much easier to type (on keyboards that don't have the "Ć" character).

**Comment by pfusik** [comment]
I also got a comment regarding confusion of two different names for the same programming language.
"Ć" and "Ci" are not different names, but alternative spellings, much like "&" vs "and".

**Comment by jedwards1211** [comment]
When I was talking about it with a friend the other day I just called it "C with an accent".
I don't mind the name but another suggestion: "C-meleon", since it can transform into any other language 😃

**Comment by er2** [comment]
If we're throwing out names, then since it's C with an acute accent, CuteC, pronounced "cutesy". Or Cd, pronounced "seed" for an intentional pun there.

</bikeshed>

**Comment by JimmyCushnie** [comment]
Another thought: officially renaming it to "Cito", same as the repo name, would be a good move IMO.

**Comment by jedwards1211** [comment]
I just realized that on macOS I can type `option-e e` to produce é, and this works for other vowels, yet `option-e c` doesn't work.  I'm going to contact Apple support about it 😁

**Comment by JimmyCushnie** [comment]
This is exactly my point about it being hard to type of US keyboards.

**Comment by jedwards1211** [comment]
I think there's room for improvement from OSes there

**Comment by JimmyCushnie** [comment]
Certainly, but that doesn't change the fact that this project's popularity is hindered by its current name.

**Comment by lawwantsin** [comment]
Someone should close this thread, before it becomes too popular.  This language is awesome and the name is fine.  I call it cito. 
And I hope it does the absolute minimum towards it's translation goal and then hardens.  Don't C++ this one.  It'll be useful for programming teachers as well.   We need more polyglots.

**Comment by Teashrock** [comment]
I wonder if I should make a programming language and name it "Ç"...

**Comment by Dingo64** [comment]
> I wonder if I should make a programming language and name it "Ç"...

Follow your dreams :)

**Comment by Dingo64** [comment]
> This is exactly my point about it being hard to type on US keyboards.

You don't need to type "Ć", just type "Ci".
Software written in the US often has problems with other than Latin alphabets. Now you can feel like hundreds of millions of people who couldn't type their native "ü, ö, ä, ó, ń, ą, â, ê, î, ô, û" for decades ;)

**Comment by JimmyCushnie** [comment]
That's fine if your goal is to frustrate anglophone programmers. However, if your goal is instead to increase the popularity of your tool and get more people using it, I maintain that calling your tool "Ć" works directly against that goal.

**Comment by thecatkitty** [comment]
Naming the language with letter Ć gives it a lot of individuality, and also helps to associate the language with its author. Also really nothing prevents you from writing Ci as @pfusik suggested (on the sidenote, in Polish *ci* and *ć* are pronounced exactly the same when isolated). Frustrating exclusively anglophone programmers is just a bonus.

**Comment by BenBE** [comment]
> Frustrating exclusively anglophone programmers is just a bonus.

We sure need an accompanying cross-platform assembler called ß going with this language …

/sarcasm

**Comment by pfusik** [comment]
A billion people spend *years* to study English as their second language.
If you feel frustrated about spending a few *minutes* to learn how to type and pronounce a single letter, it's *your* problem!

**Comment by JimmyCushnie** [comment]
I am not frustrated at all. You seem to be misunderstanding my argument. This isn't about how I personally feel, it's about allowing this project to spread throughout English-speaking communities unhindered. If you want Ć to fulfill its potential in terms of how many people and projects use it, then you have to make it easy for everyone to remember, search for, and talk about.

It's not even specifically about the accent/alphabet. I would be equally disapproving of a name like "Intermediate Language", because that name is also hard to remember/search for/talk about.

If you're not going to change the name, just close this issue. No point leaving it open if the issue won't be addressed.

**Comment by Danon** [comment]
@pfusik Do you have any alternative names in mind?

**Comment by pfusik** [comment]
@Danon I have some idea, but haven't decided yet. Why do you ask?

**Comment by Danon** [comment]
> @Danon I have some idea, but haven't decided yet. Why do you ask?

Was just curious bout what you have in mind

**Comment by danieljpetersen** [comment]
An unfortunate aspect of the name is it being easy to confuse Ć for C when quickly reading. There'd be a stronger argument in favor of keeping the name if the accented letter was not also the letter of another language.

**Comment by pfusik** [comment]
Thank you for all your remarks! I have renamed the language from Ć to Fusion and its transpiler from `cito` to `fut`. A release is coming soon. For a short URL, use https://fusion-lang.org For now it redirects to this GitHub project.

This also solves a problem of "CI" being confused for Continuous Integration.
