### ISSUE TITLE
Enum generated as Java interface

### ISSUE THREAD

**Issue by crmorello** [fusionlanguage/fut#81]
Just curious if there is a particular reason why Cito enums are generated as separate Java interfaces?
This:
```c#
public enum TestEnum { 
    A, 
    B 
}
```
Generates a separate `TestEnum.java` file that contains:
```Java
public interface TestEnum
{
	int A = 0;
	int B = 1;
}
```
I would have expected the following since the syntax is almost identical in this case
```Java
public enum TestEnum { 
    A, 
    B;
}
```

**Comment by pfusik** [comment]
Thank you for this question!

This decision was made long time ago, when Android was avoiding Java enums.
It looks like Android's reasons are [now obsolete](https://stackoverflow.com/questions/5143256/why-was-avoid-enums-where-you-only-need-ints-removed-from-androids-performanc/5264861) so I'm going to change `cito` to emit Java enums.

**Comment by pfusik** [comment]
```java
import java.util.EnumSet;

enum Inventory
{
	_GUN,
	_KNIFE,
	_KEY;
	public static final EnumSet<Inventory> NONE = EnumSet.noneOf(Inventory.class);
	public static final EnumSet<Inventory> GUN = EnumSet.of(_GUN);
	public static final EnumSet<Inventory> KNIFE = EnumSet.of(_KNIFE);
	public static final EnumSet<Inventory> WEAPONS = EnumSet.of(_GUN, _KNIFE);
	public static final EnumSet<Inventory> KEY = EnumSet.of(_KEY);

	/// The `&` operator.
	public static EnumSet<Inventory> retaining(EnumSet<Inventory> a, EnumSet<Inventory> b)
	{
		EnumSet<Inventory> result = EnumSet.copyOf(a);
		result.retainAll(b);
		return result;
	}

	/// The `|` operator.
	public static EnumSet<Inventory> adding(EnumSet<Inventory> a, EnumSet<Inventory> b)
	{
		EnumSet<Inventory> result = EnumSet.copyOf(a);
		result.addAll(b);
		return result;
	}
}
```

?

**Comment by pfusik** [comment]
Ć | Java
--- | ---
`f1 == f2` | `f1.equals(f2)`
`~f` | `EnumSet.complementOf(f)`
`f1 &= f2;` | `f1 = EnumSet.copyOf(f1); f1.retainAll(f2);`
`f1 \|= f2;` | `f1 = EnumSet.copyOf(f1); f1.addAll(f2);`
`f1.HasFlag(f2)` | `f1.containsAll(f2)`
`f1 ^ f2` (symmetric difference) | ???

**Comment by crmorello** [comment]
Ah nice, thanks for taking a look into this. The EnumSet solution looks good to me, though I don't write Java often so I'm not an authority on the matter. I think for symmetric difference most people generally rely on a library as there is no built in. There is two different implementations here to get an idea: https://rosettacode.org/wiki/Symmetric_difference#Java

**Comment by pfusik** [comment]
`EnumSet` is problematic. Assigning (integer or other enum) values to Java enum is problematic.
For now, I'm going to emit Java enums only for non-flags enums with no assigned values. Other enums will remain `interface`s with `int` constants.
